language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    
notifications:
  email:
    recipients:
      - bei.chu@almunos.upm.es
      
script: mvn verify
